name: Aula de integração contínua

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Mostra texto
        run: echo Aula Ok

      - name: Sincronia com o Glitch
        uses: kanadgupta/glitch-sync@v3.0.1
        with:
          auth-token: '${{ secrets.authToken }}'
          project-id: '${{ secrets.projectId }}'
